version: '2'
services:
    privateclasses-app:
        image: privateclasses
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://privateclasses-mysql:3306/privateclasses?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=privateclasses-elasticsearch:9300
        ports:
            - 8080:8080
    privateclasses-mysql:
        extends:
            file: mysql.yml
            service: privateclasses-mysql
    privateclasses-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: privateclasses-elasticsearch
